# The timeline UI tests (Tests/UI/Timeline), kept in their own list so Tests/CMakeLists.txt stays
# under the file-size cap.
target_sources(Tests PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTransportBarReturnToStartTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationMarkerMainTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TransportCtrlChordsTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelRulerTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelMarkerTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelZoomSnapScrollTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelTrackHeaderTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelTrackSizingTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelTrackReorderTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelTrackReorderUndoGlideTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelAppWiringTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelResizeTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelAuthoringGestureTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelToolStripTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePanel/TimelinePanelFollowPlayheadTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/CursorGlide/TimelineCursorGlideTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelinePlayheadTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineRoutingPaneTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineMidiDestinationMacroRoutingTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackDeleteConfirmTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackHeaderTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackHeaderContextMenuTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackFocusTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackMultiSelectTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackDuplicateTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackDeleteMotionTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTrackShowModuleTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineAddTrackKeyboardTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineAddTrackPickerTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipKeyboardTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipKeyboardNavTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipLane/TimelineClipLaneAreaTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipLane/TimelineClipLaneAuthoringTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipLane/TimelineClipLaneEditToolsTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipLane/TimelineClipLaneMouseTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipLane/TimelineClipLanePaintingTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipLane/TimelineClipLaneRangeTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineClipLane/TimelineClipLaneSelectionTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/MidiDestinationPickerTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationEditorTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineTransportBarTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TransportBarMidiLearnTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineRowLayoutTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesFoldTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesAddRowTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesAddMainTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesEditingTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesHeaderReadoutTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesPointBubbleTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesPointSelectionTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesPointValueFieldTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/LanePointMathTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/LanePointStretchTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesStretchTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesShapeTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesShapePaintTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/LaneShapeGeneratorTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesUnassignedTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesLoadTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesColourCursorTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesMenuTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesRetargetTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesDuplicateTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesKeyboardTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesReorderTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesLaneMainTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesAddModulatorTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesChangeSourceTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesModulatorRowTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesModulatorMainTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesModulatorEditTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesModulatorMacroRemovalTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesAmountModelTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesAmountBandTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/AutomationLanes/AutomationLanesAmountIntegrationTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineViewStateTests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/UI/Timeline/TimelineFadeMotionTests.cpp
)
