# AppUI's source list, split out of the root CMakeLists.txt (FRO62) purely to keep that file
# under the repo's 1,000-line file-size cap (scripts/check-file-sizes.sh) -- registering the
# GraphEditor split's new per-concern units pushed it over. No behavior change: paths stay
# relative to the repo root, exactly as when they sat inline in add_library(AppUI STATIC ...).
set(APPUI_SOURCES
    Source/MainComponent/MainComponent.cpp
    Source/MainComponent/MainComponent.h
    Source/MainComponent/MainComponentInternal.h
    Source/MainComponent/MainComponentCallbacks.cpp
    Source/MainComponent/MainComponentFileIO.cpp
    Source/MainComponent/MainComponentCommands.cpp
    Source/MainComponent/MainComponentPanels.cpp
    Source/MainComponent/MainComponentTimeline.cpp
    Source/MainComponent/MainComponentTrackHeaderHost.cpp
    Source/MainComponent/MainComponentTrackCreation.cpp
    Source/UserSettings.h
    Source/UI/TimelinePanelComponent.h
    Source/UI/TimelinePanelComponent.cpp
    Source/UI/TimelineRulerComponent.h
    Source/UI/TimelineRulerComponent.cpp
    Source/UI/TimelinePlayheadOverlay.h
    Source/UI/TimelinePlayheadOverlay.cpp
    Source/UI/TimelineTrackHeaderComponent.h
    Source/UI/TimelineTrackHeaderComponent.cpp
    Source/UI/TimelineTransportBar.h
    Source/UI/TimelineTransportBar.cpp
    Source/UI/TimelineClipLaneArea.h
    Source/UI/TimelineClipLaneArea.cpp
    Source/UI/ClipSelectionModel.h
    Source/UI/PianoRollComponent/PianoRollComponent.h
    Source/UI/PianoRollComponent/PianoRollComponent.cpp
    Source/UI/PianoRollComponent/PianoRollScaleAssist.cpp
    Source/UI/PianoRollComponent/PianoRollPainting.cpp
    Source/UI/PianoRollComponent/PianoRollEditTools.cpp
    Source/UI/PianoRollComponent/PianoRollAudition.cpp
    Source/UI/PianoRollComponent/PianoRollClipboardAndKeys.cpp
    Source/UI/PianoRollComponent/PianoRollMouse.cpp
    Source/UI/PianoRollComponent/PianoRollZoom.cpp
    Source/UI/NoteSelectionModel.h
    Source/UI/AutomationLaneEditor.h
    Source/UI/AutomationLaneEditor.cpp
    Source/UI/TrackColour.h
    Source/UI/TimelineViewState.h
    Source/UI/AIChatComponent.cpp
    Source/UI/AccountRow.cpp
    Source/UI/AccountRow.h
    Source/UI/PlanBadge.cpp
    Source/UI/PlanBadge.h
    Source/UI/SignInDialog.cpp
    Source/UI/SignInDialog.h
    Source/UI/ExportAudioDialog.cpp
    Source/UI/ExportAudioDialog.h
    Source/UI/GraphEditor/GraphEditor.cpp
    Source/UI/GraphEditor/GraphEditor.h
    Source/UI/GraphEditor/GraphEditorCables.cpp
    Source/UI/GraphEditor/GraphEditorConnections.cpp
    Source/UI/GraphEditor/GraphEditorSmartConnections.cpp
    Source/UI/GraphEditor/GraphEditorSmartConnectionsApply.cpp
    Source/UI/GraphEditor/GraphEditorCanvas.cpp
    Source/UI/GraphEditor/GraphEditorSelection.cpp
    Source/UI/GraphEditor/GraphEditorMacroGeometry.cpp
    Source/UI/GraphEditor/GraphEditorMacroGrouping.cpp
    Source/UI/GraphEditor/GraphEditorMacroPortSplice.cpp
    Source/UI/GraphEditor/GraphEditorChannels.cpp
    Source/UI/GraphEditor/GraphEditorMacroPorts.cpp
    Source/UI/GraphEditor/GraphEditorCommands.cpp
    Source/UI/GraphEditor/GraphEditorDragDrop.cpp
    Source/UI/GraphEditor/GraphEditorStereoWiring.cpp
    Source/UI/GraphEditor/GraphEditorPersistence.cpp
    Source/UI/ModuleComponent/ModuleComponent.cpp
    Source/UI/ModuleComponent/ModuleComponent.h
    Source/UI/ModuleComponent/ModuleComponentInternal.h
    Source/UI/ModuleComponent/ModuleComponentEQCard.cpp
    Source/UI/ModuleComponent/ModuleComponentAudioDrop.cpp
    Source/UI/ModuleComponent/ModuleComponentWavetable.cpp
    Source/UI/ModuleComponent/ModuleComponentLayout.cpp
    Source/UI/ModuleComponent/ModuleComponentPaint.cpp
    Source/UI/ModuleComponent/ModuleComponentInteraction.cpp
    Source/UI/MacroCardComponent.cpp
    Source/UI/MacroPortConfigDialog.cpp
    Source/UI/MacroCardComponent.h
    Source/UI/FrequencyResponseComponent.h
    Source/UI/FrequencyGrid.h
    Source/UI/EQCurveComponent.h
    Source/UI/EQWindow.h
    Source/UI/SampleWaveformComponent.h
    Source/UI/WavetableDisplayComponent.h
    Source/UI/TriggerMeterComponent.h
    Source/UI/ThresholdControlComponent.h
    Source/UI/ModMatrixComponent.cpp
    Source/UI/ModMatrixComponent.h
    Source/UI/SettingsWindow.cpp
    Source/UI/SettingsWindow.h
    Source/UI/WelcomeScreenComponent.cpp
    Source/UI/WelcomeScreenComponent.h
    # Plugin hosting UI (TL7-5) — native editor windows for hosted VST3/AU plugins. In AppUI (a
    # window), not Core, mirroring HostedPluginModule/HostedPluginBackend's Core placement above.
    Source/Plugin/Hosting/HostedPluginEditorWindow.cpp
    Source/Plugin/Hosting/HostedPluginEditorWindow.h
    Source/Plugin/Hosting/HostedPluginWindowManager.h
    Source/UI/AppearanceSettingsTab.cpp
    Source/UI/AppearanceSettingsTab.h
    Source/UI/FeedbackSettingsTab.cpp
    Source/UI/FeedbackSettingsTab.h
    Source/UI/PreferencesSettingsTab.cpp
    Source/UI/PreferencesSettingsTab.h
    Source/UI/ShortcutsSettingsTab.cpp
    Source/ShortcutManager.h
    Source/Update/UpdateManager.h
)
