# AppUI's source list, split out of the root CMakeLists.txt (FRO62) purely to keep that file
# under the repo's 1,000-line file-size cap (scripts/check-file-sizes.sh) -- registering the
# GraphEditor split's new per-concern units pushed it over. No behavior change: paths stay
# relative to the repo root, exactly as when they sat inline in add_library(AppUI STATIC ...).
set(APPUI_SOURCES
    Source/MainComponent/MainComponent.cpp
    Source/MainComponent/MainComponent.h
    Source/MainComponent/MainComponentInternal.h
    Source/MainComponent/MainComponentSetup.cpp
    Source/MainComponent/MainComponentSetupToolbar.cpp
    Source/MainComponent/MainComponentSetupTimeline.cpp
    Source/MainComponent/MainComponentCallbacks.cpp
    Source/MainComponent/MainComponentFileIO.cpp
    Source/MainComponent/MainComponentCommands.cpp
    Source/MainComponent/MainComponentCommandTable.cpp
    Source/MainComponent/MainComponentPanels.cpp
    Source/MainComponent/MainComponentTimeline.cpp
    Source/MainComponent/MainComponentTrackHeaderHost.cpp
    Source/MainComponent/MainComponentTrackCreation.cpp
    Source/UserSettings.h
    Source/UI/Timeline/TimelinePanelComponent/TimelinePanelComponent.h
    Source/UI/Timeline/TimelinePanelComponent/TimelinePanelComponent.cpp
    Source/UI/Timeline/TimelinePanelComponent/TimelinePanelStrips.cpp
    Source/UI/Timeline/TimelinePanelComponent/TimelinePanelClipClipboard.cpp
    Source/UI/Timeline/TimelinePanelComponent/TimelinePanelShortcuts.cpp
    Source/UI/Timeline/TimelinePanelComponent/TimelinePanelTrackHeaders.cpp
    Source/UI/Timeline/TimelinePanelComponent/TimelinePanelLayout.cpp
    Source/UI/Timeline/TimelineRulerComponent.h
    Source/UI/Timeline/TimelineRulerComponent.cpp
    Source/UI/Timeline/TimelinePlayheadOverlay.h
    Source/UI/Timeline/TimelinePlayheadOverlay.cpp
    Source/UI/Timeline/TimelineTrackHeaderComponent.h
    Source/UI/Timeline/TimelineTrackHeaderComponent.cpp
    Source/UI/Timeline/TimelineTransportBar.h
    Source/UI/Timeline/TimelineTransportBar.cpp
    Source/UI/Timeline/TimelineClipLaneArea/TimelineClipLaneArea.h
    Source/UI/Timeline/TimelineClipLaneArea/TimelineClipLaneArea.cpp
    Source/UI/Timeline/TimelineClipLaneArea/TimelineClipLaneInternal.h
    Source/UI/Timeline/TimelineClipLaneArea/TimelineClipLanePainting.cpp
    Source/UI/Timeline/TimelineClipLaneArea/TimelineClipLaneMouse.cpp
    Source/UI/Timeline/TimelineClipLaneArea/TimelineClipLaneSelection.cpp
    Source/UI/Timeline/TimelineClipLaneArea/TimelineClipLaneEditTools.cpp
    Source/UI/Timeline/ClipSelectionModel.h
    Source/UI/PianoRoll/PianoRollComponent/PianoRollComponent.h
    Source/UI/PianoRoll/PianoRollComponent/PianoRollComponent.cpp
    Source/UI/PianoRoll/PianoRollComponent/PianoRollScaleAssist.cpp
    Source/UI/PianoRoll/PianoRollComponent/PianoRollPainting.cpp
    Source/UI/PianoRoll/PianoRollComponent/PianoRollEditTools.cpp
    Source/UI/PianoRoll/PianoRollComponent/PianoRollAudition.cpp
    Source/UI/PianoRoll/PianoRollComponent/PianoRollClipboardAndKeys.cpp
    Source/UI/PianoRoll/PianoRollComponent/PianoRollMouse.cpp
    Source/UI/PianoRoll/PianoRollComponent/PianoRollZoom.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryComponent.h
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryComponent.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibrarySearch.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryRows.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryCollapse.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryLayout.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryPainting.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryInput.cpp
    Source/UI/Library/ModuleLibraryComponent/ModuleLibraryHelpPopover.cpp
    Source/UI/PianoRoll/NoteSelectionModel.h
    Source/UI/Timeline/AutomationLaneEditor.h
    Source/UI/Timeline/AutomationLaneEditor.cpp
    Source/UI/Timeline/TrackColour.h
    Source/UI/Timeline/TimelineViewState.h
    Source/UI/Assistant/AIChatComponent/AIChatComponent.cpp
    Source/UI/Assistant/AIChatComponent/AIChatComponentMessageList.cpp
    Source/UI/Assistant/AIChatComponent/AIChatComponentSending.cpp
    Source/UI/Assistant/AIChatComponent/AIChatComponentProvider.cpp
    Source/UI/Assistant/AIChatComponent/AIChatComponentHistory.cpp
    Source/UI/Assistant/AccountRow.cpp
    Source/UI/Assistant/AccountRow.h
    Source/UI/Assistant/PlanBadge.cpp
    Source/UI/Assistant/PlanBadge.h
    Source/UI/Assistant/SignInDialog.cpp
    Source/UI/Assistant/SignInDialog.h
    Source/UI/Chrome/ExportAudioDialog.cpp
    Source/UI/Chrome/ExportAudioDialog.h
    Source/UI/Graph/GraphEditor/GraphEditor.cpp
    Source/UI/Graph/GraphEditor/GraphEditor.h
    Source/UI/Graph/GraphEditor/GraphEditorCables.cpp
    Source/UI/Graph/GraphEditor/GraphEditorConnections.cpp
    Source/UI/Graph/GraphEditor/GraphEditorSmartConnections.cpp
    Source/UI/Graph/GraphEditor/GraphEditorSmartConnectionsApply.cpp
    Source/UI/Graph/GraphEditor/GraphEditorCanvas.cpp
    Source/UI/Graph/GraphEditor/GraphEditorSelection.cpp
    Source/UI/Graph/GraphEditor/GraphEditorMacroGeometry.cpp
    Source/UI/Graph/GraphEditor/GraphEditorMacroGrouping.cpp
    Source/UI/Graph/GraphEditor/GraphEditorMacroPortSplice.cpp
    Source/UI/Graph/GraphEditor/GraphEditorChannels.cpp
    Source/UI/Graph/GraphEditor/GraphEditorMacroPorts.cpp
    Source/UI/Graph/GraphEditor/GraphEditorCommands.cpp
    Source/UI/Graph/GraphEditor/GraphEditorDragDrop.cpp
    Source/UI/Graph/GraphEditor/GraphEditorStereoWiring.cpp
    Source/UI/Graph/GraphEditor/GraphEditorPersistence.cpp
    Source/UI/Graph/ModuleComponent/ModuleComponent.cpp
    Source/UI/Graph/ModuleComponent/ModuleComponent.h
    Source/UI/Graph/ModuleComponent/ModuleComponentInternal.h
    Source/UI/Graph/ModuleComponent/ModuleComponentEQCard.cpp
    Source/UI/Graph/ModuleComponent/ModuleComponentAudioDrop.cpp
    Source/UI/Graph/ModuleComponent/ModuleComponentWavetable.cpp
    Source/UI/Graph/ModuleComponent/ModuleComponentLayout.cpp
    Source/UI/Graph/ModuleComponent/ModuleComponentPaint.cpp
    Source/UI/Graph/ModuleComponent/ModuleComponentInteraction.cpp
    Source/UI/Macros/MacroCardComponent.cpp
    Source/UI/Macros/MacroPortConfigDialog.cpp
    Source/UI/Macros/MacroCardComponent.h
    Source/UI/ModuleViews/FrequencyResponseComponent.h
    Source/UI/ModuleViews/FrequencyGrid.h
    Source/UI/ModuleViews/EQCurveComponent.h
    Source/UI/ModuleViews/EQWindow.h
    Source/UI/ModuleViews/SampleWaveformComponent.h
    Source/UI/ModuleViews/WavetableDisplayComponent.h
    Source/UI/ModuleViews/TriggerMeterComponent.h
    Source/UI/ModuleViews/ThresholdControlComponent.h
    Source/UI/Graph/ModMatrixComponent.cpp
    Source/UI/Graph/ModMatrixComponent.h
    Source/UI/Settings/SettingsWindow.cpp
    Source/UI/Settings/SettingsWindow.h
    Source/UI/Chrome/WelcomeScreenComponent.cpp
    Source/UI/Chrome/WelcomeScreenComponent.h
    # Plugin hosting UI (TL7-5) — native editor windows for hosted VST3/AU plugins. In AppUI (a
    # window), not Core, mirroring HostedPluginModule/HostedPluginBackend's Core placement above.
    Source/Plugin/Hosting/HostedPluginEditorWindow.cpp
    Source/Plugin/Hosting/HostedPluginEditorWindow.h
    Source/Plugin/Hosting/HostedPluginWindowManager.h
    Source/UI/Settings/AppearanceSettingsTab.cpp
    Source/UI/Settings/AppearanceSettingsTab.h
    Source/UI/Settings/FeedbackSettingsTab.cpp
    Source/UI/Settings/FeedbackSettingsTab.h
    Source/UI/Settings/PreferencesSettingsTab.cpp
    Source/UI/Settings/PreferencesSettingsTab.h
    Source/UI/Settings/ShortcutsSettingsTab.cpp
    Source/ShortcutManager/AppCommands.h
    Source/ShortcutManager/ShortcutManager.h
    Source/Update/UpdateManager.h
)
